THEME_MODULE = github.com/nginxinc/nginx-hugo-theme
## Pulls the current theme version from the Netlify settings
THEME_VERSION = $(NGINX_THEME_VERSION)
NETLIFY_DEPLOY_URL = ${DEPLOY_PRIME_URL}

.PHONY: all all-staging all-dev all-local clean hugo-mod build-production build-staging build-dev docs-drafts docs deploy-preview

all: hugo-mod build-production

all-staging: hugo-mod build-staging

all-dev: hugo-mod build-dev

all-local: clean hugo-mod build-production

# Removes the public directory generated by the `hugo` command
clean:
	if [[ -d ${PWD}/public ]] ; then rm -rf ${PWD}/public && echo "Removed public directory" ; else echo "Did not find a public directory to remove" ; fi

hugo-mod:
	hugo mod get $(THEME_MODULE)@v$(THEME_VERSION)

build-production:
	hugo --gc -e production
	cp _redirects public/_redirects
	
build-staging:
	hugo --gc -e staging
	cp _redirects_staging public/_redirects

build-dev:
	hugo --gc -e development
	cp _redirects_dev public/_redirects

docs-drafts:
	hugo server -D --disableFastRender

docs:
	hugo server --disableFastRender

deploy-preview: hugo-mod
	hugo --gc -b ${NETLIFY_DEPLOY_URL}
